#+STYLE: <link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
#+STYLE: <style>.example { font-size: 14px; } p { font-size: 16px; line-height: 150%; }</style>
#+STYLE: <style>h1, h2, h3, h4, h5, h6, .example { margin-top: 15px; margin-bottom: 15px; }</style>
#+HTML: <div class="container">
#+TITLE: DOI Content Negotiation

* Introduction

  DOIs provide a persistent link to content. They identify many types of work, 
  from journal articles to research data sets. Typically, someone interacting with 
  DOIs will be a researcher, who will resolve DOIs found in scholarly references 
  to content using the @<a href='http://dx.doi.org'>DOI resolver@</a>. Such
  researchers may not even realise they are using DOIs and the resolver
  since they may be follow dx.doi.org web links without interacting with the URL
  itself.

  Yet DOIs can provide more than a permanent, indirect link to content. DOI 
  registration agencies such as CrossRef and DataCite collect bibliographic metadata 
  about the works they link to. This metadata can be retrieved from the DOI resolver
  too, using content negotation to request a particular representation of the metadata.

* Redirection

  The DOI resolver at dx.doi.org will normally redirect a user to the resource
  location of a DOI. For example, the DOI "10.1126/science.169.3946.635"
  redirects to a landing page describing the article, "The Structure of Ordinary Water".
  Content negotiated requests to dx.doi.org that ask for a content type which isn't
  "text/html" will be redirected to a metadata service hosted by DOI's registration
  agency. At time of writing, CrossRef and DataCite support content negotiated DOIs via
  http://data.crossref.org and http://data.datacite.org. mEDRA DOIs are also supported
  via the CrossRef metadata service.

  #+HTML: <div class="row"><div class="span6 offset3">
  #+BEGIN_EXAMPLE
         GET "Accept: text/html"
  http://dx.doi.org/10.1126/science.169.3946.635

                     |
                     |
                     |
                     V

         Publisher landing page 
  http://www.sciencemag.org/content/169/3946/635
  #+END_EXAMPLE
  #+HTML: </div></div>
  
  Normal browser requests or explicit requests for text/html redirect to the content's
  landing page.

  #+HTML: <div class="row"><div class="span6 offset3">
  #+BEGIN_EXAMPLE
         GET "Accept: application/rdf+xml"
  http://dx.doi.org/10.1126/science.169.3946.635 
                     
                     |
                     |
                     |
                     V

         CrossRef metadata service 
  http://data.crossref.org/10.1126/science.169.3946.635
  #+END_EXAMPLE
  #+HTML: </div></div>

  Requests for a data type redirect to a RA metadata service.

* What is Content Negotiation?

  Content negotiation allows a web browser or some other computer program to request
  a particular representation of a web resource. The DOI resolver uses content
  negotation to provide different representations of metadata associated with DOIs.

** The Accept Header

   Making a content negotiated request requires the use of a HTTP header, "Accept".
   Acceptable content types are declared in the Accept header, each with an optional
   "quality" value indicating its relative suitability. For example, a client that
   wishes to receive citeproc JSON if it is available, but which can also handle
   RDF XML if citeproc JSON is unavailable, would make a request with an Accept
   header listing both "application/citeproc+json" and "application/rdf+xml":

   #+BEGIN_EXAMPLE
   $ curl -LH "Accept: application/rdf+xml;q=0.5, application/citeproc+json;q=1.0" http://dx.doi.org/10.5555/test_doi
   #+END_EXAMPLE

   This request favours citeproc JSON but will accept RDF XML if citeproc is unavailable.
   The q values are optional. The request could have been written without them. The
   order of content types then becomes important; more suitable content types should
   be placed at the front of the Accept header.

   #+BEGIN_EXAMPLE
   $ curl -LH "Accept: application/citeproc+json, application/rdf+xml" http://dx.doi.org/10.5555/test_doi
   #+END_EXAMPLE

** Response Codes

   #+ATTR_HTML: class="table table-bordered table-striped"
   | Code | Meaning                                                          |
   |------+------------------------------------------------------------------|
   |  200 | The request was OK.                                              |
   |  400 | The DOI requested is malformed, or some other unspecified error. |
   |  404 | The DOI requested doesn't exist.                                 |
   |  406 | Data service can't serve any of your requested content types.    |

   Individual RA metadata services may utilise additional response codes but they will
   always use the response codes above in event of the case described.

* Supported Content Types

  Currently two DOI registration agencies have implemented content negotation for their 
  DOIs: CrossRef and DataCite. They support a number of metadata content types, some of
  which are common to both RAs:

  #+ATTR_HTML: class="table table-bordered table-striped"
  | Format            | Content Type              |
  |-------------------+---------------------------|
  | RDF XML           | application/rdf+xml       |
  | Turtle            | text/turtle               |
  | Handle Admin JSON | application/handle+json   |
  | Citeproc JSON     | application/citeproc+json |

  Each RA also supports specific, non-standard content types. Using content
  negotation it is possible to make a request that favours RA-specific content types
  and will degrade to respond with a more standard content type if it is not
  available. See the examples below.

* Determine a DOI's Registration Agency

  Each DOI has a handle record that is available through DOI content negotiation.
  Handle records contain metadata about a DOI, including the name of registration
  agencies that control DOIs. Handle records can be retreived via the text/handle
  content type:

  #+BEGIN_EXAMPLE
  $ curl -LH "Accept: application/handle+json" http://dx.doi.org/10.5555/test_doi
  #+END_EXAMPLE

* CrossRef and DataCite

  CrossRef and DataCite implement additional content types and features. For
  documentation see:

  - http://data.datacite.org
  - http://data.crossref.org

* Getting Help

  Please contact labs@crossref.org or cn@datacite.org for support.

#+HTML: </div>
